version: '3.8'

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php-mvc-app
        volumes:
            - .:/var/www/html
        networks:
            - app-network

    nginx:
        image: nginx:latest
        container_name: nginx-server
        ports:
            - "8080:80"
        volumes:
            - .:/var/www/html
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - app-network

    db:
        image: mysql:8.0
        container_name: mysql-db
        environment:
            MYSQL_HOST: db
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: newishop
            MYSQL_PASSWORD: root
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - "3306:3306"
        networks:
            - app-network

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            PMA_HOST: db
        ports:
            - "8081:80"
        networks:
            - app-network

networks:
    app-network:
        driver: bridge

volumes:
    db_data:
        driver: local